config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {sessions: "admins/sessions"}
  devise_for :users, controllers: {sessions: "users/sessions"}
  get 'order_details/new'

  get 'order_details/show'

  get 'order_details/destroy'

  get 'payment/send'

  get 'payment/receive'

  resources :posts do
  	resources :comments
  end

  root 'posts#index'

  get '/octavio' => 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :image, presence: true
	has_many :comments, dependent: :destroy

  	has_attached_file :image, styles: { :medium => "640x" }
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  protect_from_forgery :except => [:index]

  # GET /posts
  # GET /posts.json
  def index
    if user_signed_in?
      @posts = current_user.posts
    else
      @posts = Post.all
    end
  end

  # GET /posts/1
  # GET /posts/1.json

  def index
          @posts = Post.all
            respond_to do |format|
                format.json do
                    render :json => @posts, :callback => params[:callback]
                end
                format.html
            end
     # if admin_signed_in?
     # else
         # @asesorias = current_user.asesorias
      #end
  end

  def show
  end

  # GET /posts/new
  def new
      @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        flash[:success] = "Post was successfully created."
        format.html { redirect_to @post }
        format.json { render :show, status: :created, location: @post }
      else
        flash[:error] = "There was a problem while saving the post"
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        flash[:success] = "Post was successfully updated."
        format.html { redirect_to @post }
        format.json { render :show, status: :ok, location: @post }
      else
        flash[:error] = "There was a problem while updating the post"
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end
    #holo
    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:image, :title, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image, class: 'col-sm-2 control-label'  %>
    <div class="col-sm-6">
      <%= f.file_field :image %>
    </div>
  </div>

  <div class="medium-6 columns">
    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title, :class => "validate[required]" %>
    </div>
  </div>
  <div class="large-10 columns">
    <div class="field">
      <%= f.label :body %><br>
      <%= f.text_area :body, :class => "validate[required]" %>
    </div>
  </div>
  <section class="row">
    <div class="small-4 columns">
      <div class="actions">
        <%= f.submit 'Aceptar', :class => 'button tiny success radius' %>
      </div>
    <div>
  <section>
<% end %>

app/views/posts/_navigation.html.erb
<nav class="top-bar" data-topbar role="navigation">
	<ul class="title-area">
		<li class="name">
			<h1>Twitstagram</h1>
		</li>
	</ul>
		<section class="top-bar-section">
			<ul class="left">
				<li class="has-dropdown not-click"> <a href="#">Posts</a>
					<ul class="dropdown">
						<li class="parent-link show-for-small-only"> <a class="parent-link js-generated" href="#">Posts</a> </li>
						<li> <label>Posts</label> </li>
						<li> <%= link_to 'Ver', controller: '/posts', action: 'index' %> </li>
						<% if user_signed_in? %>
						<li> <%= link_to 'Nuevo', controller: '/posts', action: 'new' %> </li>
						<% end %>
					</ul>
				</li>
			<li class="divider"> </li>
			</ul>

			<ul class='right'>
        		<% if user_signed_in? %>
        			<li class="active"><a href="#">Logged in as <strong><%= current_user.email %></strong></a></li>
        			<li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>
           			<li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
            		<li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
        		<% else %>
        				<% if admin_signed_in? %>
        			<li class="active"><a href="#">Logged in as <strong><%= current_admin.email %></strong></a></li>
           			<li><%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %></li>
            		<li><%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link' %></li>
        				<% else %>
            		<li><% link_to "Sign up as Admin", new_admin_registration_path, :class => 'navbar-link' %></li>
            		<li><% link_to "Login as Admin", new_admin_session_path, :class => 'navbar-link' %></li>
            			<% end %>
            		<% if !admin_signed_in? %>
            		<li><%= link_to "Sign up as User", new_user_registration_path, :class => 'navbar-link' %></li>
            		<li><%= link_to "Login as User", new_user_session_path, :class => 'navbar-link' %></li>
            		<% end %>
            	<% end %>
 
            		
            </ul>
		</section>
</nav>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <% if admin_signed_in? %>
        <th>Usurio</th>
      <% end %>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td>
            <% if admin_signed_in? %>
          <% if post.user_id %>
            <a href="#" data-reveal-id="post-<%= post.id %>"> Usuario </a>
            <div id="post-<%= post.id %>" class="reveal-modal" data-reveal>
              <%= User.find(post.user_id).email %>
              <a class="close-reveal-modal">&#215;</a>
            </div>
          <% end %>
            <% end %>
        </td>
        <td>
          <% if post.body %>
            <a href="#" data-reveal-id="post-<%= post.id %>"> Show Body</a>
            <div id="post-<%= post.id %>" class="reveal-modal" data-reveal>
              <%= post.body %>
              <a class="close-reveal-modal">&#215;</a>
            </div>
          <% end %>
        </td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
<%= link_to 'New Post', new_post_path %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= image_tag(@post.image.url(:medium)) %>

<div id="comments" class='medium-6 colums'>
	<%= render :partial => @post.comments.reverse %>
</div>

<%= form_for([@post,Comment.new],remote: true) do |f| %>
	<p class='large-10 columns'> <%= f.label :body, "New Comment" %> <br/>
		<%= f.text_area :body %>
	</p>
	<br/>
	<p> <%= f.submit "Add Comment", :class => 'button tiny success radius' %> </p>

<% end %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>